steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tangibel-frontend:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tangibel-frontend:latest'
      - '.'
  
  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/tangibel-frontend:$BUILD_ID'
  
  # Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/tangibel-frontend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tangibel-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tangibel-frontend:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'STRIPE_SECRET_KEY=${_STRIPE_SECRET_KEY},STRIPE_WEBHOOK_SECRET=${_STRIPE_WEBHOOK_SECRET},SUPABASE_SERVICE_ROLE_KEY=${_SUPABASE_SERVICE_ROLE_KEY},STRIPE_GARAGE_MONTHLY_PRICE_ID=${_STRIPE_GARAGE_MONTHLY_PRICE_ID},STRIPE_GARAGE_YEARLY_PRICE_ID=${_STRIPE_GARAGE_YEARLY_PRICE_ID},STRIPE_SHOWROOM_MONTHLY_PRICE_ID=${_STRIPE_SHOWROOM_MONTHLY_PRICE_ID},STRIPE_SHOWROOM_YEARLY_PRICE_ID=${_STRIPE_SHOWROOM_YEARLY_PRICE_ID},STRIPE_DEALERSHIP_MONTHLY_PRICE_ID=${_STRIPE_DEALERSHIP_MONTHLY_PRICE_ID},STRIPE_DEALERSHIP_YEARLY_PRICE_ID=${_STRIPE_DEALERSHIP_YEARLY_PRICE_ID},STRIPE_FACTORY_MONTHLY_PRICE_ID=${_STRIPE_FACTORY_MONTHLY_PRICE_ID},STRIPE_FACTORY_YEARLY_PRICE_ID=${_STRIPE_FACTORY_YEARLY_PRICE_ID}'

images:
  - 'gcr.io/$PROJECT_ID/tangibel-frontend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/tangibel-frontend:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
