'use client'

import Link from 'next/link'
import PublicNav from '@/components/PublicNav'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-black text-white">
      <PublicNav />

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-8 pt-28 pb-16">
        <h1 className="text-3xl sm:text-4xl font-thin tracking-tight mb-2">
          Tangibel Terms of Use
        </h1>
        <p className="text-sm text-gray-400 mb-12">Last updated: November 26, 2025</p>

        <div className="prose prose-invert prose-sm max-w-none space-y-8 text-gray-300 font-light leading-relaxed">
          <p>
            PLEASE READ THESE TERMS CAREFULLY. These Terms of Use ("Terms") are a legal agreement between you ("you," "your," or "Customer") and Tangibel, Inc. ("Tangibel," "we," "us," or "our") governing your access to and use of Tangibel's products and services, including websites, applications, APIs, SDKs, demos, documentation, and fulfillment integrations (collectively, the "Service" or "Platform"). By accessing or using the Service you agree to be bound by these Terms. If you do not agree, do not use the Service.
          </p>

          {/* Section 1 */}
          <section>
            <h2 className="text-xl font-light text-white mb-4">1. DEFINITIONS</h2>
            <ul className="space-y-3 list-none pl-0">
              <li><strong className="text-white">Account.</strong> Your registered account on the Platform. Accounts enable usage tracking, billing, saving designs, and managing orders.</li>
              <li><strong className="text-white">Customer Data.</strong> Information you supply to the Platform that relates to identifiable individuals or to your business, including inputs, uploads, shipping details, payment identifiers (handled by third‑party processors), and metadata.</li>
              <li><strong className="text-white">User Content.</strong> All content you provide to or generate within the Service, including text prompts, images, reference files, design parameters, 3D models, and any Outputs generated by the Service in response.</li>
              <li><strong className="text-white">Outputs.</strong> 3D models, previews, mesh files (e.g., STL/OBJ), and manufactured physical items (3D‑printed parts, models, toys, etc.) created by or through the Service based on your inputs. Outputs are distinct from Tangibel's models, code, and training data.</li>
              <li><strong className="text-white">Order.</strong> A transaction in which you request the manufacture and shipment of physical products derived from your Outputs.</li>
              <li><strong className="text-white">Manufacturing Partners.</strong> Independent third‑party providers that perform 3D printing, finishing, and shipping of physical products ordered through the Platform.</li>
              <li><strong className="text-white">Credits.</strong> Any internal unit Tangibel uses to meter paid features, generations, or API calls. Credits may be promotional, trial, or purchased.</li>
              <li><strong className="text-white">Order Form.</strong> A signed or electronic ordering document describing purchased services, pricing, term, and any special terms that override these Terms.</li>
              <li><strong className="text-white">DPA.</strong> Data Processing Addendum — a separate agreement that governs the processing of Customer Data when Tangibel acts as a processor.</li>
            </ul>
          </section>

          {/* Section 2 */}
          <section>
            <h2 className="text-xl font-light text-white mb-4">2. ADMISSION; ACCEPTANCE; CHANGES</h2>
            <ul className="space-y-3 list-none pl-0">
              <li><strong className="text-white">Acceptance.</strong> By creating an Account, clicking an "I accept" button, or using the Service, you accept these Terms and any referenced policies (including our Privacy Policy and Acceptable Use Policy). If you do not agree, do not use the Service.</li>
              <li><strong className="text-white">Material changes.</strong> We may amend these Terms. Material changes will be posted with a new effective date and, where reasonably possible, we will provide at least fourteen (14) days' advance notice (e.g., via email or in‑product notice). Continued use after the effective date constitutes acceptance of the revised Terms.</li>
              <li><strong className="text-white">Order Forms control.</strong> If you have a separately executed Order Form or Master Services Agreement with Tangibel, that signed agreement controls to the extent of any direct conflict with these public Terms.</li>
            </ul>
          </section>

          {/* Section 3 */}
          <section>
            <h2 className="text-xl font-light text-white mb-4">3. ELIGIBILITY; ACCOUNT REGISTRATION; SECURITY</h2>
            <ul className="space-y-3 list-none pl-0">
              <li><strong className="text-white">Eligibility.</strong> You must be at least 18 years old, or have the legal authority to bind the entity on whose behalf you act. If you are under the age of majority, you may use the Service only with the consent and supervision of a parent or legal guardian who accepts these Terms on your behalf.</li>
              <li><strong className="text-white">Registration.</strong> You agree to provide accurate registration information and to keep it current. Use of shared credentials or purchasing for unauthorized third parties is prohibited unless expressly permitted in writing.</li>
              <li><strong className="text-white">Security.</strong> You are responsible for maintaining the confidentiality of your credentials and API keys, and for all activity under your Account. Notify us at support@tangibel.io immediately of any suspected unauthorized use. Tangibel may suspend access while investigating suspected compromise.</li>
            </ul>
          </section>

          {/* Section 4 */}
          <section>
            <h2 className="text-xl font-light text-white mb-4">4. SERVICES; ORDER FORMS; SCOPE</h2>
            <ul className="space-y-3 list-none pl-0">
              <li><strong className="text-white">Service description.</strong> Tangibel provides tools that allow users to (a) generate or upload images and other inputs, (b) convert such inputs into 3D models using AI and related software, and (c) purchase custom 3D‑printed products manufactured and shipped by Manufacturing Partners. Features and capabilities may evolve over time.</li>
              <li><strong className="text-white">Order Forms.</strong> Paid subscriptions, enterprise integrations, and bespoke services may be governed by Order Forms specifying scope, fees, term, and any special obligations. Order Forms signed by both parties supersede conflicting public Terms for that engagement.</li>
            </ul>
          </section>

          {/* Section 5 */}
          <section>
            <h2 className="text-xl font-light text-white mb-4">5. PLATFORM IP vs. OUTPUTS</h2>
            <ul className="space-y-3 list-none pl-0">
              <li><strong className="text-white">Tangibel ownership.</strong> Tangibel retains all ownership rights in the Platform, including software, models, model checkpoints, weights, training data, designs, documentation, visual identity, and all other proprietary materials. Nothing in these Terms transfers ownership of Tangibel's technology to you.</li>
              <li><strong className="text-white">Your Outputs.</strong> Subject to these Terms and third‑party rights, Tangibel assigns to you, as between you and Tangibel, all right, title, and interest Tangibel may have in the digital Outputs (3D models, meshes, previews) generated specifically for you, excluding Tangibel's underlying models, software, and training data.</li>
              <li><strong className="text-white">License to Outputs.</strong> Subject to your compliance with these Terms, Tangibel grants you a worldwide, perpetual, royalty‑free, transferable, non‑exclusive license to use, reproduce, modify, distribute, display, and commercialize your Outputs, including incorporating them into products you sell (e.g., collectible models, toys, art objects), without additional royalties to Tangibel.</li>
              <li><strong className="text-white">Limitations.</strong> You may not:
                <ul className="mt-2 ml-4 space-y-1 list-disc">
                  <li>Claim ownership of Tangibel's underlying models, code, or training data.</li>
                  <li>Attempt to reconstruct or extract model weights, training datasets, or other trade secrets from the Service.</li>
                  <li>Resell or redistribute Outputs as undifferentiated stock libraries (e.g., large packs of raw 3D models sold primarily as "Tangibel‑generated assets") without a separate written license from Tangibel (contact legal@tangibel.io).</li>
                </ul>
              </li>
            </ul>
          </section>

          {/* Section 6 */}
          <section>
            <h2 className="text-xl font-light text-white mb-4">6. USER CONTENT — REPRESENTATIONS, RIGHTS, OPERATIONAL LICENSE</h2>
            <ul className="space-y-3 list-none pl-0">
              <li><strong className="text-white">Your representations.</strong> By submitting User Content, you represent and warrant that:
                <ul className="mt-2 ml-4 space-y-1 list-disc">
                  <li>You own or have obtained all necessary rights, licenses, and permissions to submit such content to the Service and to authorize Tangibel to use it as described in these Terms.</li>
                  <li>Your content does not infringe any third‑party rights (e.g., vehicle designs, logos, characters, brands) unless you have explicit permission.</li>
                  <li>You have obtained any required parental or guardian consent where minors are involved.</li>
                </ul>
              </li>
              <li><strong className="text-white">Operational license.</strong> You grant Tangibel a worldwide, non‑exclusive, royalty‑free license to host, store, process, modify (e.g., for mesh repair, scaling, and printability checks), and retransmit your User Content and Outputs as necessary to:
                <ul className="mt-2 ml-4 space-y-1 list-disc">
                  <li>Provide, maintain, secure, and improve the Service.</li>
                  <li>Fulfill Orders through Manufacturing Partners.</li>
                  <li>Detect, prevent, and investigate fraud, abuse, and security incidents.</li>
                </ul>
                This license is for operational purposes only and does not transfer ownership of your content to Tangibel.
              </li>
              <li><strong className="text-white">Responsibility.</strong> You are solely responsible for your User Content, Outputs, and use of the Service, including compliance with copyright, design rights, privacy, export controls, and consumer protection laws. If you lack necessary rights in any content, do not submit it.</li>
            </ul>
          </section>

          {/* Section 7 */}
          <section>
            <h2 className="text-xl font-light text-white mb-4">7. ACCEPTABLE USE POLICY (AUP)</h2>
            <p className="mb-4">You may use the Service only for lawful purposes and in compliance with the rules below. Violations may result in content removal, Order cancellation, Account suspension, or termination.</p>
            <ul className="space-y-3 list-none pl-0">
              <li><strong className="text-white">No illegal activity.</strong> Do not use the Service to create, promote, or facilitate illegal acts (e.g., fraud, trafficking, or evasion of law).</li>
              <li><strong className="text-white">No weapons or safety‑critical parts.</strong> You must not use the Service to design, manufacture, or attempt to manufacture:
                <ul className="mt-2 ml-4 space-y-1 list-disc">
                  <li>Firearms, weapons, weapon components, ammunition, or accessories intended to affect lethality or concealment.</li>
                  <li>Safety‑critical vehicle or aircraft components (e.g., brakes, steering, suspension, structural parts).</li>
                  <li>Medical devices, implants, or other regulated equipment unless explicitly authorized in a written agreement.</li>
                </ul>
              </li>
              <li><strong className="text-white">No hate, harassment, or exploitation.</strong> Do not use the Service to produce content that is hateful, harassing, incites violence, or exploits or harms minors (including toys or figures depicting minors in sexualized or abusive contexts).</li>
              <li><strong className="text-white">No impersonation or non‑consensual likenesses.</strong> Do not generate or upload content that misuses a real person's name, likeness, or identity without consent, particularly where it could be misleading, defamatory, or harmful.</li>
              <li><strong className="text-white">No IP circumvention.</strong> Do not use the Service to recreate protected designs, characters, logos, or other copyrighted/trademarked works unless you hold or have obtained the necessary rights. For example, do not generate and print replicas of branded cars, movie characters, or trademarked logos without authorization.</li>
              <li><strong className="text-white">No extraction of model internals.</strong> Do not attempt to reverse engineer, decompile, or extract model weights, training data, or proprietary algorithms.</li>
              <li><strong className="text-white">No abusive automation or rate‑limit evasion.</strong> Do not use bots or scripts to circumvent usage limits, monitoring, or billing. Use APIs within published rate limits; contact us if you need higher throughput.</li>
            </ul>
            <p className="mt-4">Tangibel reserves the right to investigate and act on suspected violations of this AUP, including removing content, canceling Orders, suspending or terminating Accounts, and notifying law enforcement where appropriate.</p>
          </section>

          {/* Section 8 */}
          <section>
            <h2 className="text-xl font-light text-white mb-4">8. BILLING, PAYMENTS, REFUNDS</h2>
            <ul className="space-y-3 list-none pl-0">
              <li><strong className="text-white">Fees and taxes.</strong> You agree to pay all fees and charges associated with your use of the Service, including subscription fees, per‑use or per‑print fees, shipping, taxes, duties, and any other amounts shown at checkout or described in an Order Form. Prices are subject to change.</li>
              <li><strong className="text-white">Payment processing.</strong> Payments are processed by third‑party providers (e.g., Stripe). You authorize Tangibel and its processors to charge your selected payment method. You represent that you are authorized to use that method.</li>
              <li><strong className="text-white">Subscriptions.</strong> If you enroll in a subscription plan:
                <ul className="mt-2 ml-4 space-y-1 list-disc">
                  <li>Your subscription will auto‑renew at the then‑current price unless canceled before the renewal date.</li>
                  <li>You may cancel at any time via your Account; cancellation takes effect at the end of the current billing period.</li>
                  <li>Subscription fees are generally non‑refundable except where required by law or explicitly stated.</li>
                </ul>
              </li>
              <li><strong className="text-white">Custom orders & refunds.</strong> Because each physical product is custom‑manufactured:
                <ul className="mt-2 ml-4 space-y-1 list-disc">
                  <li>We generally do not offer refunds for design or configuration choices you later dislike, or minor cosmetic imperfections within stated tolerances.</li>
                  <li>We may, at our discretion or as required by law, offer a refund, account credit, or free reprint if the item is defective beyond reasonable tolerance, significantly deviates from the approved design, material, or dimensions, or is damaged in transit.</li>
                  <li>You must notify us with photos and a description of the issue within 14 days from delivery.</li>
                </ul>
              </li>
              <li><strong className="text-white">Billing disputes.</strong> Billing disputes must be raised within thirty (30) days of the charge, with supporting information. While investigating, Tangibel may provisionally suspend the contested amount but is not obligated to issue a refund until the investigation is complete.</li>
            </ul>
          </section>


          {/* Section 9 */}
          <section>
            <h2 className="text-xl font-light text-white mb-4">9. SECURITY, DATA PROTECTION & DPA</h2>
            <ul className="space-y-3 list-none pl-0">
              <li><strong className="text-white">Security posture.</strong> Tangibel uses commercially reasonable security measures, including TLS in transit, access controls, logging, and standard operational safeguards. No system is perfectly secure; you should avoid uploading highly sensitive regulated data (e.g., health records, financial account numbers) unless there is a signed agreement explicitly addressing such data.</li>
              <li><strong className="text-white">Data retention & deletion.</strong> We retain Customer Data as needed to operate the Service and meet legal, accounting, and security obligations. You may request deletion of certain data; Tangibel will process such requests consistent with our Privacy Policy and any applicable DPA.</li>
              <li><strong className="text-white">Training use.</strong> For self‑serve tiers, Tangibel may use de‑identified or aggregated usage data to improve models and features, as described in our Privacy Policy. Enterprise or regulated customers may negotiate restrictions in a DPA; where a DPA or Order Form states that we will not use Customer Data for training, that commitment governs.</li>
              <li><strong className="text-white">Subprocessors & transfers.</strong> Tangibel uses third‑party vendors for hosting, payments, analytics, and manufacturing integrations. International data transfers will use lawful mechanisms where required. Enterprise customers may review a list of subprocessors under NDA and negotiate reasonable objections.</li>
              <li><strong className="text-white">Breach notification.</strong> In the event of a confirmed personal data breach affecting Customer Data, Tangibel will notify affected customers without undue delay and cooperate as required by applicable law and any DPA.</li>
            </ul>
          </section>

          {/* Section 10 */}
          <section>
            <h2 className="text-xl font-light text-white mb-4">10. AVAILABILITY, SUPPORT & BETA FEATURES</h2>
            <ul className="space-y-3 list-none pl-0">
              <li><strong className="text-white">Availability.</strong> For public plans, Tangibel targets high availability but does not guarantee specific uptime. Formal SLAs and credits may be provided only under signed enterprise agreements.</li>
              <li><strong className="text-white">Support.</strong> You can contact support at support@tangibel.io. Public plan response times are on a best‑effort basis; enterprise response and resolution targets may be specified in an Order Form.</li>
              <li><strong className="text-white">Beta features.</strong> Beta, experimental, or preview features are provided "AS IS," may be changed or removed at any time, and may not be covered by any SLA.</li>
            </ul>
          </section>

          {/* Section 11 */}
          <section>
            <h2 className="text-xl font-light text-white mb-4">11. INTELLECTUAL PROPERTY, TRADEMARKS & ATTRIBUTION</h2>
            <ul className="space-y-3 list-none pl-0">
              <li><strong className="text-white">Trademarks.</strong> "Tangibel" and associated logos are trademarks of Tangibel, Inc. You may not use our marks without prior written permission, except to truthfully refer to the Service.</li>
              <li><strong className="text-white">Attribution.</strong> We generally do not require attribution, but certain features or integrations may require specific attributions or notices. Where applicable, these requirements will be stated in the documentation.</li>
            </ul>
          </section>

          {/* Section 12 */}
          <section>
            <h2 className="text-xl font-light text-white mb-4">12. IP, PRODUCT, AND OTHER INDEMNIFICATION</h2>
            <p className="mb-4"><strong className="text-white">Your indemnity.</strong> You agree to indemnify, defend, and hold harmless Tangibel, its officers, directors, employees, and agents from and against any claims, damages, losses, liabilities, and expenses (including reasonable attorneys' fees) arising from:</p>
            <ul className="ml-4 space-y-1 list-disc mb-4">
              <li>Your User Content or Outputs;</li>
              <li>Your use, sale, or distribution of any digital or physical products derived from the Service;</li>
              <li>Your breach of these Terms or applicable law; or</li>
              <li>Any allegation that your content or products infringe or misappropriate any third‑party rights.</li>
            </ul>
            <p>You will promptly notify Tangibel of any such claim and cooperate with Tangibel in the defense.</p>
            <p className="mt-4">Tangibel does not provide a general IP indemnity under these public Terms. Any Tangibel indemnity obligations must be expressly agreed in a signed Order Form or MSA.</p>
          </section>

          {/* Section 13 */}
          <section>
            <h2 className="text-xl font-light text-white mb-4">13. DISCLAIMERS</h2>
            <p className="mb-4">To the maximum extent permitted by law:</p>
            <ul className="ml-4 space-y-2 list-disc">
              <li>The Service, including all AI models, 3D tools, Outputs, and manufactured products, is provided "AS IS" and "AS AVAILABLE."</li>
              <li>Tangibel disclaims all warranties, express or implied, including merchantability, fitness for a particular purpose, non‑infringement, and any warranties arising from course of dealing or usage of trade.</li>
              <li>Tangibel does not warrant that Outputs will be unique, accurate, or free of third‑party IP claims; that designs will be technically printable or suitable for your specific application; or that the Service will be uninterrupted, secure, or error‑free.</li>
              <li>You are responsible for validating the suitability and safety of any design or product for your intended use.</li>
            </ul>
          </section>

          {/* Section 14 */}
          <section>
            <h2 className="text-xl font-light text-white mb-4">14. LIMITATION OF LIABILITY</h2>
            <p className="mb-4">To the fullest extent permitted by law:</p>
            <ul className="ml-4 space-y-2 list-disc">
              <li>Tangibel's total aggregate liability for all claims arising out of or relating to the Service or these Terms will not exceed one hundred U.S. dollars (USD $100).</li>
              <li>Tangibel will not be liable for any indirect, incidental, special, punitive, or consequential damages, or for any loss of profits, revenue, data, or goodwill, even if advised of the possibility of such damages.</li>
              <li>Some jurisdictions do not allow certain exclusions or limitations; in such cases, the limitations apply only to the extent permitted by applicable law.</li>
            </ul>
          </section>

          {/* Section 15 */}
          <section>
            <h2 className="text-xl font-light text-white mb-4">15. SUSPENSION, TERMINATION & EFFECT</h2>
            <ul className="space-y-3 list-none pl-0">
              <li><strong className="text-white">Suspension.</strong> Tangibel may suspend or restrict your access to the Service (in whole or part) for violations of these Terms, suspected fraud or abuse, security concerns, or nonpayment.</li>
              <li><strong className="text-white">Termination.</strong> Either party may terminate an Order Form or Account for material breach if the breach is not cured within thirty (30) days after written notice, or immediately if the breach is not curable or involves serious policy/legal violations.</li>
              <li><strong className="text-white">Post‑termination.</strong> Upon termination:
                <ul className="mt-2 ml-4 space-y-1 list-disc">
                  <li>Your right to access the Service ceases.</li>
                  <li>You remain responsible for all fees incurred before termination.</li>
                  <li>Outputs you already received or downloaded remain licensed to you under Section 5, subject to continuing obligations (IP respect, indemnity, etc.).</li>
                  <li>Sections that by their nature should survive (including ownership, license grants to Tangibel, payment obligations, disclaimers, limitations of liability, and indemnities) will continue in effect.</li>
                </ul>
              </li>
            </ul>
          </section>

          {/* Section 16 */}
          <section>
            <h2 className="text-xl font-light text-white mb-4">16. DISPUTE RESOLUTION; GOVERNING LAW</h2>
            <ul className="space-y-3 list-none pl-0">
              <li><strong className="text-white">Informal resolution.</strong> Before initiating any formal dispute, contact support@tangibel.io or legal@tangibel.io to attempt good‑faith resolution.</li>
              <li><strong className="text-white">Governing law.</strong> These Terms are governed by the laws of the State of Delaware, without regard to conflict‑of‑law principles.</li>
              <li><strong className="text-white">Arbitration / forum.</strong> Except for claims that may be brought in small‑claims court, any dispute arising out of or relating to these Terms or the Service will be resolved by binding individual arbitration under the rules of JAMS. You and Tangibel waive any right to participate in class or representative actions.</li>
            </ul>
          </section>

          {/* Section 17 */}
          <section>
            <h2 className="text-xl font-light text-white mb-4">17. NOTICES; DMCA; CONTACT</h2>
            <ul className="space-y-3 list-none pl-0">
              <li><strong className="text-white">Notices.</strong> Legal notices to Tangibel may be sent to legal@tangibel.io. We may provide notices to you via email, in‑product messaging, or by posting on the Service.</li>
              <li><strong className="text-white">DMCA.</strong> If you believe content on the Service infringes your copyright, send a notice to legal@tangibel.io with the information required by applicable copyright law (e.g., DMCA in the U.S.). We may remove or disable access to the allegedly infringing content and follow applicable counter‑notice procedures.</li>
              <li><strong className="text-white">Contact.</strong>
                <div className="mt-2 ml-4">
                  Tangibel, Inc.<br />
                  Cambridge, MA<br />
                  legal@tangibel.io<br />
                  support@tangibel.io
                </div>
              </li>
            </ul>
          </section>

          {/* Section 18 */}
          <section>
            <h2 className="text-xl font-light text-white mb-4">18. MISCELLANEOUS</h2>
            <ul className="space-y-3 list-none pl-0">
              <li><strong className="text-white">Severability.</strong> If any provision of these Terms is held invalid or unenforceable, the remaining provisions will remain in full force, and the invalid provision will be replaced with a valid provision that best reflects the parties' original intent.</li>
              <li><strong className="text-white">Assignment.</strong> You may not assign or transfer these Terms without Tangibel's prior written consent. Tangibel may assign these Terms in connection with a merger, acquisition, corporate reorganization, or sale of assets.</li>
              <li><strong className="text-white">Entire agreement.</strong> These Terms, together with any applicable Order Forms and our Privacy Policy, constitute the entire agreement between you and Tangibel regarding the Service and supersede any prior agreements on that subject.</li>
            </ul>
          </section>
        </div>

        {/* Back to home */}
        <div className="mt-16 pt-8 border-t border-white/10">
          <Link href="/" className="text-sm text-gray-400 hover:text-white transition-colors">
            ← Back to Home
          </Link>
        </div>
      </div>
    </div>
  )
}
